### ISSUE TITLE
No funciona

### ISSUE THREAD

**Issue by alfieoriginal** [vk496/IPTVspain#1]
Los enlaces bit.ly no cargan correctamente el fichero de canales, ademas la guia parece no estar funcionando aun no usando el acortador.

**Comment by vk496** [comment]
Buenas,

¿Qué reproductor usas? Desde Kodi todo me funciona correctamente...

Salu2

El 7 de junio de 2019 14:51:00 CEST, alfieoriginal <notifications@github.com> escribió:
>Los enlaces bit.ly no cargan correctamente el fichero de canales,
>ademas la guia parece no estar funcionando aun no usando el acortador.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/vk496/IPTVspain/issues/1

-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.

**Comment by alfieoriginal** [comment]
Uso IPTV simple en Kodi. La guia llevaba algunos dias sin cargar y hoy ya no aparecian tampoco los canales. Solo he conseguido que carguen usando el fichero raw, pero la guia sigue sin cargar.

**Comment by alfieoriginal** [comment]
Hola de nuevo, no sé si has podido mirar lo de la guía, el XML no contiene datos

**Comment by vk496** [comment]
Buenas,

El problema está relacionado con la generación del xml por parte de WebGrab. Ojearé por qué está fallando y avisaré por aquí....

**Comment by vk496** [comment]
Hola de nuevo,

Parece ser que plus.es cambió ligeramente su estructura, por eso no se generaba el EGP desde hace unos días.

En el build de mañana debería funcionar nuevamente...

**Comment by vk496** [comment]
Todo vuelve a funcionar. Gracias por reportar
