### ISSUE TITLE
Numeración de canales intuitiva

### ISSUE THREAD

**Issue by alfieoriginal** [vk496/IPTVspain#3]
Sugiero una reordenación de canales más intuitiva, situando los nacionales:
#3 Antena3
#4 Cuatro
#5 Telecinco

**Comment by alfieoriginal** [comment]
La Sexta que antes ocupaba el #6, se ha visto desplazada al #8.
Mas intuitivo sería volver a ponerlo en #6

**Comment by vk496** [comment]
@alfieoriginal Oks, esta tarde lo cambio y aplico inmediatamente
