### ISSUE TITLE
EPG Telemadrid

### ISSUE THREAD

**Issue by alfieoriginal** [vk496/IPTVspain#4]
¿Es posible añadir la guía de Telemadrid?

**Comment by alfieoriginal** [comment]
Hola el EPG de Telemadrid sigue sin aparecer.

**Comment by vk496** [comment]
@alfieoriginal Gracias por avisar. Miraré a ver que pasa

**Comment by alfieoriginal** [comment]
Epg de telemadrid visible en Rbpi tras actualizar iptvsimple en ultima version de Libreelec. Debe ser que antes no le gustaba por algún motivo. Cierro hilo.
