### ISSUE TITLE
Añadir Teledeporte

### ISSUE THREAD

**Issue by alfieoriginal** [vk496/IPTVspain#5]
http://hlsliveamdgl1-lh.akamaihd.net/i/hlsdvrlive_1@39732/master.m3u8 y su EPG

**Comment by vk496** [comment]
Gracias por tu aporte @alfieoriginal 

Esta noche se desplegarán automáticamente los cambios y mañana estarían disponibles.

Salu2

**Comment by alfieoriginal** [comment]
Gracias por los cambios! aunque hay un par de cosas que no se han solucionado del todo.
