### ISSUE TITLE
La 1 no funciona

### ISSUE THREAD

**Issue by Kaylebor** [vk496/IPTVspain#7]
La 1 no funciona usando esta lista.

Encontré otro m3u8 que parece funcionar: 
http://hlsliveamdgl7-lh.akamaihd.net/i/hlsdvrlive_1@583042/master.m3u8

**Comment by vk496** [comment]
Acabo de comprobar el que se usa actualmente y también funciona. Es posible que haya sido en una emisión concreta?

**Comment by Kaylebor** [comment]
Sí, parece que ciertas emisiones no funcionan por copyright, o eso decía en la web oficial.
Adicionalmente, el que encontré yo realmente no está bien, lo he comprobado y no coincide...

¿El actual de la 1 es http://hlsliveamdgl7-lh.akamaihd.net/i/hlslive_1@583043/master.m3u8? Porque en VLC por ejemplo no me abre.
En el navegador me devuelve:

``` An error occurred while processing your request.

Reference #181.3c291102.1580073750.bee8a78 ```

**Comment by vk496** [comment]
Puedo abrirlo sin problemas. Si sigues teniendo el problema, no dudes en abrir de nuevo el issue
