### ISSUE TITLE
Guía de Canal Extremadura

### ISSUE THREAD

**Issue by Berto9050** [vk496/IPTVspain#8]
Hola.

Este es el enlace de la guía de Canal Extremadura SAT, que es la emisión que se puede ver por internet. http://www.movistarplus.es/canal/canal-extremadura-sat?id=EXTREM
La que estás usando en el archivo guide.xml es con el id "EXTRE", y el correcto es el id "EXTREM".

Un saludo.

**Comment by vk496** [comment]
Gracias por el aviso!
