### ISSUE TITLE
Añadir Urban Revolution TV

### ISSUE THREAD

**Issue by ea5iva** [vk496/IPTVspain#9]
Buenos días,
Este canal aparece en algunas listas IPTV de España como Urban Revolution TV y en otras como uRV TV, su página web es www.urbanrevolution.es y  la URL de la emisión es https://www.urbanrevolution.es:444/live/5e6d8470a3832/index.m3u8

El logo es 
![logourbanrevolution](https://user-images.githubusercontent.com/66835149/84512390-33c1d880-acc8-11ea-9f7e-2a45272522bd.png)

**Comment by vk496** [comment]
@ea5iva Muchas gracias. Ando escaso de tiempo para hacer el PR estos días. Mañana lo cambio 👍

**Comment by ea5iva** [comment]
Gracias!!-- Enviado desde mi teléfono Android con GMX Mail. Por favor, disculpe mi brevedad.El 18/6/20, 21:13 Valentin <notifications@github.com> escribió:

   
  @ea5iva Muchas gracias. Ando escaso de tiempo para hacer el PR estos días. Mañana lo cambio 👍
